package com.shanghai.tcm.myapplication.model.db.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.tcm.myapplication.bean.GoldItemBean;

import com.shanghai.tcm.myapplication.model.db.bean.GoldItemBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goldItemBeanDaoConfig;

    private final GoldItemBeanDao goldItemBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goldItemBeanDaoConfig = daoConfigMap.get(GoldItemBeanDao.class).clone();
        goldItemBeanDaoConfig.initIdentityScope(type);

        goldItemBeanDao = new GoldItemBeanDao(goldItemBeanDaoConfig, this);

        registerDao(GoldItemBean.class, goldItemBeanDao);
    }
    
    public void clear() {
        goldItemBeanDaoConfig.clearIdentityScope();
    }

    public GoldItemBeanDao getGoldItemBeanDao() {
        return goldItemBeanDao;
    }

}
